services:
  app:
    container_name: wodt-platform
    image: wodt-platform
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${EXPOSED_PORT:-4567}:${EXPOSED_PORT:-4567}"
    environment:
      - EXPOSED_PORT=${EXPOSED_PORT:-4567}
      - PLATFORM_EXPOSED_URL=${PLATFORM_EXPOSED_URL:-http://localhost:4567}
    network_mode: host  # Assumes Linux host for access to WebSocket on host
